/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a mainwindowadaptor -i gui/MainWindow.h -l MainWindow /home/runner/work/keepassxc/keepassxc/src/gui/org.keepassxc.KeePassXC.MainWindow.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MAINWINDOWADAPTOR_H
#define MAINWINDOWADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "gui/MainWindow.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.keepassxc.KeePassXC.MainWindow
 */
class MainWindowAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.keepassxc.KeePassXC.MainWindow")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.keepassxc.KeePassXC.MainWindow\">\n"
"    <method name=\"openDatabase\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"fileName\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"pw\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"keyFile\"/>\n"
"    </method>\n"
"    <method name=\"openDatabase\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"fileName\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"pw\"/>\n"
"    </method>\n"
"    <method name=\"openDatabase\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"fileName\"/>\n"
"    </method>\n"
"    <method name=\"appExit\"/>\n"
"    <method name=\"isHardwareKeySupported\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"hardwareKeySupported\"/>\n"
"    </method>\n"
"    <method name=\"refreshHardwareKeys\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"found\"/>\n"
"    </method>\n"
"    <method name=\"lockAllDatabases\"/>\n"
"    <method name=\"closeAllDatabases\"/>\n"
"  </interface>\n"
        "")
public:
    MainWindowAdaptor(MainWindow *parent);
    virtual ~MainWindowAdaptor();

    inline MainWindow *parent() const
    { return static_cast<MainWindow *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void appExit();
    void closeAllDatabases();
    bool isHardwareKeySupported();
    void lockAllDatabases();
    void openDatabase(const QString &fileName);
    void openDatabase(const QString &fileName, const QString &pw);
    void openDatabase(const QString &fileName, const QString &pw, const QString &keyFile);
    bool refreshHardwareKeys();
Q_SIGNALS: // SIGNALS
};

#endif
