/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a mainwindowadaptor -i gui/MainWindow.h -l MainWindow /home/runner/work/keepassxc/keepassxc/src/gui/org.keepassxc.KeePassXC.MainWindow.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "mainwindowadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MainWindowAdaptor
 */

MainWindowAdaptor::MainWindowAdaptor(MainWindow *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MainWindowAdaptor::~MainWindowAdaptor()
{
    // destructor
}

void MainWindowAdaptor::appExit()
{
    // handle method call org.keepassxc.KeePassXC.MainWindow.appExit
    parent()->appExit();
}

void MainWindowAdaptor::closeAllDatabases()
{
    // handle method call org.keepassxc.KeePassXC.MainWindow.closeAllDatabases
    parent()->closeAllDatabases();
}

bool MainWindowAdaptor::isHardwareKeySupported()
{
    // handle method call org.keepassxc.KeePassXC.MainWindow.isHardwareKeySupported
    return parent()->isHardwareKeySupported();
}

void MainWindowAdaptor::lockAllDatabases()
{
    // handle method call org.keepassxc.KeePassXC.MainWindow.lockAllDatabases
    parent()->lockAllDatabases();
}

void MainWindowAdaptor::openDatabase(const QString &fileName)
{
    // handle method call org.keepassxc.KeePassXC.MainWindow.openDatabase
    parent()->openDatabase(fileName);
}

void MainWindowAdaptor::openDatabase(const QString &fileName, const QString &pw)
{
    // handle method call org.keepassxc.KeePassXC.MainWindow.openDatabase
    parent()->openDatabase(fileName, pw);
}

void MainWindowAdaptor::openDatabase(const QString &fileName, const QString &pw, const QString &keyFile)
{
    // handle method call org.keepassxc.KeePassXC.MainWindow.openDatabase
    parent()->openDatabase(fileName, pw, keyFile);
}

bool MainWindowAdaptor::refreshHardwareKeys()
{
    // handle method call org.keepassxc.KeePassXC.MainWindow.refreshHardwareKeys
    return parent()->refreshHardwareKeys();
}


#include "mainwindowadaptor.moc"
