/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -i quickunlock/PolkitDbusTypes.h -p polkit_dbus /home/runner/work/keepassxc/keepassxc/src/quickunlock/dbus/org.freedesktop.PolicyKit1.Authority.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef POLKIT_DBUS_H
#define POLKIT_DBUS_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "quickunlock/PolkitDbusTypes.h"

/*
 * Proxy class for interface org.freedesktop.PolicyKit1.Authority
 */
class OrgFreedesktopPolicyKit1AuthorityInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.PolicyKit1.Authority"; }

public:
    OrgFreedesktopPolicyKit1AuthorityInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgFreedesktopPolicyKit1AuthorityInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<PolkitAuthorizationResults> CheckAuthorization(PolkitSubject subject, const QString &action_id, const QMap<QString, QString> &details, uint flags, const QString &cancellation_id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(subject) << QVariant::fromValue(action_id) << QVariant::fromValue(details) << QVariant::fromValue(flags) << QVariant::fromValue(cancellation_id);
        return asyncCallWithArgumentList(QStringLiteral("CheckAuthorization"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace freedesktop {
    namespace PolicyKit1 {
      typedef ::OrgFreedesktopPolicyKit1AuthorityInterface Authority;
    }
  }
}
#endif
