/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -i quickunlock/PolkitDbusTypes.h -p polkit_dbus /home/runner/work/keepassxc/keepassxc/src/quickunlock/dbus/org.freedesktop.PolicyKit1.Authority.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "polkit_dbus.h"

/*
 * Implementation of interface class OrgFreedesktopPolicyKit1AuthorityInterface
 */

OrgFreedesktopPolicyKit1AuthorityInterface::OrgFreedesktopPolicyKit1AuthorityInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopPolicyKit1AuthorityInterface::~OrgFreedesktopPolicyKit1AuthorityInterface()
{
}


#include "polkit_dbus.moc"
