'\" t
.\"     Title: keepassxc
.\"    Author: KeePassXC Team
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2020-08-31
.\"    Manual: General Commands Manual
.\"    Source: KeePassXC 2.8.0-snapshot
.\"  Language: English
.\"
.TH "KEEPASSXC" "1" "2020-08-31" "KeePassXC 2.8.0\-snapshot" "General Commands Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
keepassxc \- a modern open\-source password manager
.SH "SYNOPSIS"
.sp
\fBkeepassxc\fP [\fIoptions\fP] [\fIfilename(s)\fP]
.SH "DESCRIPTION"
.sp
\fBKeePassXC\fP is a free/open\-source password manager or safe which helps you to manage your passwords securely.
The complete database is always encrypted with the industry\-standard AES (also known as Rijndael) encryption algorithm using a 256\-bit key.
KeePassXC uses a database format that is compatible with KeePass Password Safe.
Your database works offline and requires no internet connection.
.SH "OPTIONS"
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Displays this help.
.RE
.sp
\fB\-\-help\-all\fP
.RS 4
Displays help including Qt specific options.
.RE
.sp
\fB\-v\fP, \fB\-\-version\fP
.RS 4
Displays version information.
.RE
.sp
\fB\-\-config\fP <\fIconfig\fP>
.RS 4
Path to a custom config file.
.RE
.sp
\fB\-\-localconfig\fP <\fIlocalconfig\fP>
.RS 4
Path to a custom local config file.
.RE
.sp
\fB\-\-lock\fP
.RS 4
Locks all open databases.
.RE
.sp
\fB\-\-keyfile\fP <\fIkeyfile\fP>
.RS 4
Key file of the database.
.RE
.sp
\fB\-\-pw\-stdin\fP
.RS 4
Reads password of the database from stdin.
.RE
.sp
\fB\-\-minimized\fP
.RS 4
Starts KeePassXC minimized to the system tray.
.RE
.sp
\fB\-\-debug\-info\fP
.RS 4
Displays debugging information.
.RE
.SH "NOTES"
.sp
\fBProject homepage\fP
.RS 4
.URL "https://keepassxc.org" "" ""
.RE
.sp
\fBQuickStart Guide\fP
.RS 4
.URL "https://keepassxc.org/docs/KeePassXC_GettingStarted.html" "" ""
.RE
.sp
\fBUser Guide\fP
.RS 4
.URL "https://keepassxc.org/docs/KeePassXC_UserGuide.html" "" ""
.RE
.sp
\fBGit repository\fP
.RS 4
.URL "https://github.com/keepassxreboot/keepassxc.git" "" ""
.RE
.SH "AUTHOR"
.sp
This manual page was originally written by Janek Bevendorff \c
.MTO "janek\(atjbev.net" "" "."
.SH "REPORTING BUGS"
.sp
Bugs and feature requests can be reported on GitHub at \c
.URL "https://github.com/keepassxreboot/keepassxc/issues" "" "."
.SH "COPYRIGHT"
.sp
Copyright (C) 2016\-2020 KeePassXC Team \c
.MTO "team\(atkeepassxc.org" "" ""
.sp
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License, either version 2 or version 3.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.sp
\fBkeepassxc\-cli\fP(1)
.SH "AUTHOR"
.sp
KeePassXC Team