.TH KEEPASSXC-CLI 1 "Jan 19, 2018"

.SH NAME
keepassxc-cli \- command line interface for the \fBKeePassXC\fP password manager.

.SH SYNOPSIS
.B keepassxc-cli
.RI [ options ]
.I command

.SH DESCRIPTION
\fBkeepassxc-cli\fP is the command line interface for the \fBKeePassXC\fP password manager. It provides the ability to query and modify the entries of a KeePass database, directly from the command line.

.SH COMMANDS

.IP "add [options] <database> <entry>"
Adds a new entry to a database. A password can be generated (\fI-g\fP option), or a prompt can be displayed to input the password (\fI-p\fP option).

.IP "clip [options] <database> <entry> [timeout]"
Copies the password of a database entry to the clipboard. If multiple entries with the same name exist in different groups, only the password for the first one is going to be copied. For copying the password of an entry in a specific group, the group path to the entry should be specified as well, instead of just the name. Optionally, a timeout in seconds can be specified to automatically clear the clipboard.

.IP "diceware [options] <words>"
Generate a random diceware passphrase.

.IP "edit [options] <database> <entry>"
Edits a database entry. A password can be generated (\fI-g\fP option), or a prompt can be displayed to input the password (\fI-p\fP option).

.IP "estimate [options] [password]"
Estimates the entropy of a password. The password to estimate can be provided as a positional argument, or using the standard input.

.IP "extract [options] <database>"
Extracts and prints the contents of a database to standard output in XML format.

.IP "locate [options] <database> <term>"
Locates all the entries that match a specific search term in a database.

.IP "ls [options] <database> [group]"
Lists the contents of a group in a database. If no group is specified, it will default to the root group.

.IP "merge [options] <database1> <database2>"
Merges two databases together. The first database file is going to be replaced by the result of the merge, for that reason it is advisable to keep a backup of the two database files before attempting a merge. In the case that both databases make use of the same credentials, the \fI--same-credentials\fP or \fI-s\fP option can be used.

.IP "passgen [options] <length>"
Generate a random password

.IP "rm [options] <database> <entry>"
Removes an entry from a database. If the database has a recycle bin, the entry will be moved there. If the entry is already in the recycle bin, it will be removed permanently.

.IP "show [options] <database> <entry>"
Shows the title, username, password, URL and notes of a database entry. Regarding the occurrence of multiple entries with the same name in different groups, everything stated in the \fIclip\fP command section also applies here.

.SH OPTIONS

.SS "General options"

.IP "-k, --key-file <path>"
Specifies a path to a key file for unlocking the database. In a merge operation this option is used to specify the key file path for the first database.

.IP "-h, --help"
Displays help information.

.IP "-v, --version"
Shows the program version.


.SS "Merge options"

.IP "-f, --key-file-from <path>"
Path of the key file for the second database.

.IP "-s, --same-credentials"
Use the same credentials for unlocking both database.


.SS "Add and edit options"

.IP "-u, --username <username>"
Specify the username of the entry.

.IP "--url <url>"
Specify the URL of the entry.

.IP "-p, --password-prompt"
Use a password prompt for the entry's password.

.IP "-g, --generate"
Generate a new password for the entry.

.IP "-l, --password-length"
Specify the length of the password to generate.


.SS "Edit options"

.IP "-t, --title <title>"
Specify the title of the entry.


.SS "Estimate options"

.IP "-a, --advanced"
Perform advanced analysis on the password.


.SS "Show options"

.IP "-a, --attributes <attribute>..."
Names of the attributes to show. This option can be specified more than once,
with each attribute shown one-per-line in the given order. If no attributes are
specified, a summary of the default attributes is given.


.SS "Diceware options"

.IP "-w, --wordlist <path>"
Path of the wordlist for the diceware generator. The wordlist must have > 1000 words,
otherwise the program will fail. If the wordlist has < 4000 words a warning will
be printed to STDERR.


.SS "PassGen options"

.IP "-l"
Use lowercase characters for the password generator

.IP "-u"
Use uppercase characters for the password generator

.IP "-n"
Use numbers characters for the password generator

.IP "-s"
Use special characters for the password generator

.IP "-e"
Use extended ascii characters for the password generator



.SH REPORTING BUGS
Bugs and feature requests can be reported on GitHub at https://github.com/keepassxreboot/keepassxc/issues.

.SH AUTHOR
This manual page was written by Manolis Agkopian <m.agkopian@gmail.com>.
