/* config-keepassx-tests.h. Generated by cmake from config-keepassx-tests.h.cmake */

#ifndef KEEPASSX_CONFIG_TESTS_H
#define KEEPASSX_CONFIG_TESTS_H

#define KEEPASSX_TEST_DATA_DIR "/home/runner/work/keepassxc/keepassxc/tests/data"

#define WITH_XC_AUTOTYPE
/* #undef WITH_XC_YUBIKEY */

#endif // KEEPASSX_CONFIG_TESTS_H
