# CMake generated Testfile for 
# Source directory: /home/runner/work/keepassxc/keepassxc/tests
# Build directory: /home/runner/work/keepassxc/keepassxc/_codeql_build_dir/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testgroup "testgroup")
set_tests_properties(testgroup PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;103;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkdbx2 "testkdbx2")
set_tests_properties(testkdbx2 PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;106;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkdbx3 "testkdbx3")
set_tests_properties(testkdbx3 PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;109;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkdbx4 "testkdbx4")
set_tests_properties(testkdbx4 PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;112;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkeys "testkeys")
set_tests_properties(testkeys PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;115;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testgroupmodel "testgroupmodel")
set_tests_properties(testgroupmodel PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;118;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testentrymodel "testentrymodel")
set_tests_properties(testentrymodel PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;121;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testcryptohash "testcryptohash")
set_tests_properties(testcryptohash PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;124;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testsymmetriccipher "testsymmetriccipher")
set_tests_properties(testsymmetriccipher PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;127;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testhashedblockstream "testhashedblockstream")
set_tests_properties(testhashedblockstream PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;130;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkeepass2randomstream "testkeepass2randomstream")
set_tests_properties(testkeepass2randomstream PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;133;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testmodified "testmodified")
set_tests_properties(testmodified PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;136;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testdeletedobjects "testdeletedobjects")
set_tests_properties(testdeletedobjects PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;139;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkeepass1reader "testkeepass1reader")
set_tests_properties(testkeepass1reader PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;142;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testimports "testimports")
set_tests_properties(testimports PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;145;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testautotype "testautotype")
set_tests_properties(testautotype PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;156;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testentry "testentry")
set_tests_properties(testentry PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;170;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testmerge "testmerge")
set_tests_properties(testmerge PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;173;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testpasswordgenerator "testpasswordgenerator")
set_tests_properties(testpasswordgenerator PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;176;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testpasswordhealth "testpasswordhealth")
set_tests_properties(testpasswordhealth PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;179;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testpassphrasegenerator "testpassphrasegenerator")
set_tests_properties(testpassphrasegenerator PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;182;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testhibp "testhibp")
set_tests_properties(testhibp PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;185;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testtotp "testtotp")
set_tests_properties(testtotp PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;188;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testbase32 "testbase32")
set_tests_properties(testbase32 PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;191;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testcsvparser "testcsvparser")
set_tests_properties(testcsvparser PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;194;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testrandomgenerator "testrandomgenerator")
set_tests_properties(testrandomgenerator PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;197;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testentrysearcher "testentrysearcher")
set_tests_properties(testentrysearcher PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;200;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testcsvexporter "testcsvexporter")
set_tests_properties(testcsvexporter PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;203;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testdatabase "testdatabase")
set_tests_properties(testdatabase PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;217;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testtools "testtools")
set_tests_properties(testtools PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;220;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testconfig "testconfig")
set_tests_properties(testconfig PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;223;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testcli "testcli")
set_tests_properties(testcli PROPERTIES  ENVIRONMENT "LANG=en_US.UTF-8" _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;245;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
