== License and Disclaimers

KeePassXC is licensed with the
https://github.com/keepassxreboot/keepassxc/blob/master/LICENSE.GPL-3[GNU General Public License Version 3].
All copyrights and additional licenses are recorded in
https://github.com/keepassxreboot/keepassxc/blob/master/COPYING[COPYING].

=== Disclaimer of Warranty

THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.
Except when otherwise stated in writing the copyright holders and/or other parties provide the program "as is" without
Warranty of any kind, either expressed or implied, including, but not limited to, the implied warranties of
Merchantability and fitness for a particular purpose. The entire risk as to the quality and performance of the program
Is with you. Should the program prove defective, you assume the cost of all necessary servicing, repair or correction.

=== Limitation of Liability

In no event unless required by applicable law or agreed to in writing will any copyright holder, or any other party
Who modifies and/or conveys the program as permitted above, be liable to you for damages, including any general,
Special, incidental or consequential damages arising out of the use or inability to use the program (including but not
Limited to loss of data or data being rendered inaccurate or losses sustained by you or third parties or a failure of
The program to operate with any other programs), even if such holder or other party has been advised of the possibility
Of such damages.
