.TH KEEPASSXC 1 "Oct 25, 2019"
.SH NAME
keepassxc \- password manager

.SH SYNOPSIS
.B keepassxc
.B [
.I options
.B ] [
.I filename(s)
.B ]

.SH DESCRIPTION
\fBKeePassXC\fP is a free/open-source password manager or safe which helps you to manage your passwords in a secure way. The complete database is always encrypted with the industry-standard AES (alias Rijndael) encryption algorithm using a 256 bit key. KeePassXC uses a database format that is compatible with KeePass Password Safe. Your wallet works offline and requires no Internet connection.

.SH OPTIONS
.IP "\fB-h\fP, \fB--help\fP"
Displays this help.

.IP "\fB-v\fP, \fB--version\fP"
Displays version information.

.IP "\fB--config\fP <config>"
Path to a custom config file

.IP "\fB--keyfile\fP <keyfile>"
Key file of the database

.IP "\fB--pw-stdin\fP"
Read password of the database from stdin

.IP "\fB--pw\fP, \fB--parent-window\fP <handle>"
Parent window handle

.IP "\fB--debug-info\fP"
Displays debugging information.

.SH AUTHOR
This manual page is maintained by the KeePassXC Team <team@keepassxc.org>.
