/* config-keepassx.h. Generated by cmake from config-keepassx.h.cmake */

#ifndef KEEPASSX_CONFIG_H
#define KEEPASSX_CONFIG_H

#define KEEPASSX_VERSION "${KEEPASSX_VERSION}"

#define KEEPASSX_SOURCE_DIR "${CMAKE_SOURCE_DIR}"

#cmakedefine HAVE_PR_SET_DUMPABLE 1
#cmakedefine HAVE_RLIMIT_CORE 1
#cmakedefine HAVE_PT_DENY_ATTACH 1

#endif // KEEPASSX_CONFIG_H
