/* config-keepassx.h. Generated by cmake from config-keepassx.h.cmake */

#ifndef KEEPASSX_CONFIG_H
#define KEEPASSX_CONFIG_H

#define KEEPASSX_VERSION "${KEEPASSX_VERSION}"

#define KEEPASSX_SOURCE_DIR "${CMAKE_SOURCE_DIR}"

#endif // KEEPASSX_CONFIG_H
