find_path(QRENCODE_INCLUDE_DIR qrencode.h)
find_library(QRENCODE_LIBRARY qrencode)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LibQREncode DEFAULT_MSG QRENCODE_LIBRARY QRENCODE_INCLUDE_DIR)

mark_as_advanced(QRENCODE_LIBRARY QRENCODE_INCLUDE_DIR)